stages:
  - test
  - deploy

variables:
  NODE_ENV: 'production'
  ANGULAR_CLI_VERSION: '18.2.9'
  NPM_CACHE_DIR: '$CI_PROJECT_DIR/.npm'

cache:
  paths:
    - .npm
    - dist/
    - node_modules/

before_script:
  - npm config set cache $NPM_CACHE_DIR --global
  - npm install -g @angular/cli@$ANGULAR_CLI_VERSION

run_tests:
  stage: test
  image: node:20
  script:
    - npm install -force
    - npm run build
    - npm run test
  artifacts:
    reports:
      junit: test-results.xml
    paths:
      - node_modules/
      - dist/
      - coverage/
    only:
      - main
      - develop
      - merge_requests

deploy:
  stage: deploy
  image: node:20
  script:
    - echo "Deploying to production server..."
    # Here you can add the commands to deploy your application
  only:
    - main