stages:
  - install
  - test
  - build
  - deploy

variables:
  NODE_ENV: 'production'
  ANGULAR_CLI_VERSION: '18.2.2'
  NPM_CACHE_DIR: '$CI_PROJECT_DIR/.npm'

cache:
  paths:
    - .npm
    - node_modules/

before_script:
  - npm config set cache $NPM_CACHE_DIR --global
  - npm install -g @angular/cli@$ANGULAR_CLI_VERSION

install_dependencies:
  stage: install
  image: node:20
  script:
    - npm install -force
  artifacts:
    paths:
      - node_modules/

run_tests:
  stage: test
  image: node:20
  script:
    - npm install -force
    - npm test --coverage --coverageReporters=html
  artifacts:
    reports:
      junit: test-results.xml
    paths:
      - coverage/

build_project:
  stage: build
  image: node:20
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  image: node:20
  script:
    - echo "Deploying to production server..."
    # Here you can add the commands to deploy your application
  only:
    - main