const FID_LOGGER_TRACKING_ID = 'FID-LOGGER-TRACKING-ID'
const NOT_FOUND_REQUEST_CODE = 404;
const NOT_FOUND_REQUEST_CODE_VALUE= 'MNG-FRONT-UI-FAIL';
const NOT_FOUND_REQUEST_TITLE = 'Invalid API request.'
const NOT_FOUND_REQUEST_DETAIL = 'Invalid API request, no backend API found for the request path.'

const API_FAILURE_REQUEST_CODE = 500;
const API_FAILURE_REQUEST_CODE_VALUE = 'MNG-FRONT-AP-FAIL';
const API_FAILURE_REQUEST_TITLE = 'Error in Downstream API.';
const API_FAILURE_REQUEST_DETAIL = 'Error in Downstream API, an non 2xx response was thrown when proxying downstream API.';

const CONTENT_TYPE_DEFAULT = 'application/json';

module.exports = {
  FID_LOGGER_TRACKING_ID,
  NOT_FOUND_REQUEST_CODE,
  NOT_FOUND_REQUEST_CODE_VALUE,
  NOT_FOUND_REQUEST_TITLE,
  NOT_FOUND_REQUEST_DETAIL,
  API_FAILURE_REQUEST_CODE,
  API_FAILURE_REQUEST_CODE_VALUE,
  API_FAILURE_REQUEST_TITLE,
  API_FAILURE_REQUEST_DETAIL,

  CONTENT_TYPE_DEFAULT
}
