proxy:
  http:
    host: HTTP_PROXY_HOST
    port: HTTP_PROXY_PORT
  service:
    map: API_SERVICE_MAP
    requestTimeout: API_SERVICE_REQUEST_TIMEOUT
    jobs:
      url: API_SERVICE_JOBS_MAP
      requestTimeout: API_SERVICE_REQUEST_TIMEOUT
